name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
        os:
          - "windows-latest"
        build_type:
          - "Release"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build
        run: make

      - name: Decode base64 certificate
        uses: jcesarmobile/base64-to-file-action@v1
        with:
          encoded_string: ${{ secrets.CERTIFICATE_PFX_BASE64 }}
          file_path: certificate.pfx

      - name: Sign executable
        uses: goreleaser/sign-action@v1
        with:
          artifact: ./bin/focusframe.exe
          pfx_file: certificate.pfx
          pfx_password: ${{ secrets.CERTIFICATE_PASSWORD }}
          timestamp_server_url: http://timestamp.digicert.com
