name: Build and Release Go Windows Application

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "windows-latest"

    permissions:
      packages: write
      contents: write

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      # Build the Windows executable
      - name: Build Windows executable
        run: |
          make VERSION="$(git describe --tags)"

      # Pack the ZIP Archive
      - name: Pack ZIP Archive
        run: |
          $archiveName = "FocusFrame-$(git describe --tags)-windows-amd64.zip"
          
          Move-Item -Path ./bin/FocusFrame.exe -Destination ./FocusFrame.exe
          Compress-Archive -Path "./FocusFrame.exe", 'README.md', 'LICENSE' -DestinationPath $archiveName
          
          echo "FILE_PATH=./$archiveName" >> $env:GITHUB_ENV
          echo "FILE_NAME=$archiveName" >> $env:GITHUB_ENV

      # Upload the built binary to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.FILE_PATH }}
          asset_name: ${{ env.FILE_NAME }}
          asset_content_type: application/octet-stream
