name: Build and Release Go Windows Application

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "windows-latest"

    permissions:
      packages: write
      contents: write

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      # Build the Windows executable
      - name: Build Windows executable
        run: |
          make | tee build_output.txt
          # Extract the path of the built binary from the 'make' output
          $BINARY_PATH = Select-String -Path build_output.txt -Pattern 'bin/[a-zA-Z0-9\.\-_]+\.exe' | ForEach-Object { $_.Matches.Value }
          Write-Host "BINARY_PATH=$BINARY_PATH" >> $env:GITHUB_ENV

      # Upload the built binary to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.BINARY_PATH }}
          asset_name: ${{ env.BINARY_PATH }}
          asset_content_type: application/octet-stream
